#
# Copyright 2013-2026 chronicle.software; SPDX-License-Identifier: Apache-2.0
#

# Tracing if resources are closed/released correctly.
jvm.resource.tracing=true
disable.resource.warning=true

disable.discard.warning=false
# for profiling
jvm.safepoint.enabled=false
# reduce logging of the announcer
chronicle.announcer.disable=true
pauser.minProcessors=1
# to monitor disk space every 1 second in testing
chronicle.disk.monitor.period=1

# check it can be changed in a test
chronicle.disk.monitor.threshold.percent=5
